import React,{useEffect,useMemo,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {BrowserRouter,useNavigate,useLocation} from 'react-router-dom'
import {Activity,AlertTriangle,ArrowRight,BarChart3,Bell,Building2,CalendarDays,CheckCircle2,ChevronDown,ChevronRight,CircleHelp,Clock3,Command,Database,FileText,Home,LogIn,LogOut,Menu,MessageCircle,Plus,RefreshCw,Search,ShieldCheck,Sparkles,TrendingUp,Users,WifiOff,X,Zap} from 'lucide-react'
import {api} from './api'
import './styles.css'

const HEROES=[
 {title:'Build with visibility. Deliver with confidence.',sub:'SETU brings project progress, cost signals, risk intelligence and action into one national project view.',image:'https://upload.wikimedia.org/wikipedia/commons/3/3f/Aerial_view_of_Central_Vista%2C_New_Delhi_%2C_India.jpg'},
 {title:'From project data to early action.',sub:'See what is moving, what is slipping, and where intervention can make the difference.',image:'https://upload.wikimedia.org/wikipedia/commons/4/4d/An_Aerial_view_of_the_Dhola-Sadiya_bridge_across_River_Brahmaputra%2C_inaugurated_by_the_Prime_Minister%2C_Shri_Narendra_Modi%2C_in_Assam_on_May_26%2C_2017_%282%29.jpg'},
 {title:'One bridge between data and decisions.',sub:'A modern project monitoring workspace designed for ministries, administrators and delivery teams.',image:'https://upload.wikimedia.org/wikipedia/commons/6/6b/Aerial_view_of_Ghatkopar_Metro_Station_and_Ghatkopar_Railway_Station.jpg'}
]

function App(){
 const [user,setUser]=useState(()=>{try{return JSON.parse(localStorage.getItem('setu_user'))}catch{return null}})
 const [page,setPage]=useState('dashboard')
 const [selected,setSelected]=useState(null)
 const [chatOpen,setChatOpen]=useState(false)
 const [riskProject,setRiskProject]=useState(null)
 const [toast,setToast]=useState(null)
 const nav=useNavigate(); const loc=useLocation()
 useEffect(()=>{if(!user && loc.pathname!=='/login' && loc.pathname!=='/register') nav('/login'); else if(user && (loc.pathname==='/login'||loc.pathname==='/register')) nav('/')},[user,loc.pathname])
 const go=p=>{setPage(p);setSelected(null);nav(p==='dashboard'?'/':'/'+p)}
 const login=u=>{setUser(u);nav('/')}
 const logout=()=>{localStorage.clear();setUser(null);nav('/login')}
 if(!user) return loc.pathname==='/register'?<Register onLogin={login}/>:<Login onLogin={login}/>
 return <div className="app-shell">
   <Sidebar page={page} go={go} user={user}/>
   <div className="main-shell">
     <Topbar user={user} onLogout={logout} onMenu={()=>document.body.classList.toggle('sidebar-open')} />
     <main className="content">
       {page==='dashboard'&&<Dashboard onProject={id=>{setSelected(id);setPage('project');}} onProjects={()=>go('projects')} onRisk={id=>setRiskProject(id)} onChat={()=>setChatOpen(true)} />}
       {page==='projects'&&<Projects onProject={id=>{setSelected(id);setPage('project')}} onRisk={id=>setRiskProject(id)} />}
       {page==='project'&&selected&&<ProjectDetail id={selected} onBack={()=>go('projects')} onRisk={id=>setRiskProject(id)} onChat={()=>setChatOpen(true)} />}
       {page==='alerts'&&<Alerts />}
       {page==='reports'&&<Reports />}
       {page==='admin'&&<Admin />}
     </main>
   </div>
   <button className="ask-setu" onClick={()=>setChatOpen(true)}><Sparkles size={17}/><span>Ask SETU</span></button>
   {chatOpen&&<Chatbot onClose={()=>setChatOpen(false)} />}
   {riskProject&&<RiskModal projectId={riskProject} onClose={()=>setRiskProject(null)} />}
   {toast&&<div className="toast">{toast}<button onClick={()=>setToast(null)}><X size={14}/></button></div>}
 </div>
}

function Sidebar({page,go,user}){return <aside className="sidebar">
 <div className="brand" onClick={()=>go('dashboard')}><div className="brand-mark"><span>S</span></div><div><strong>SETU</strong><small>Project Intelligence</small></div></div>
 <div className="nav-section"><span>WORKSPACE</span>
  <NavItem active={page==='dashboard'} icon={<Home/>} label="Overview" onClick={()=>go('dashboard')}/>
  <NavItem active={page==='projects'} icon={<Building2/>} label="Projects" onClick={()=>go('projects')}/>
  <NavItem active={page==='alerts'} icon={<Bell/>} label="Alerts" onClick={()=>go('alerts')}/>
  <NavItem active={page==='reports'} icon={<BarChart3/>} label="Reports" onClick={()=>go('reports')}/>
 </div>
 <div className="nav-section"><span>MANAGEMENT</span>
  <NavItem active={page==='admin'} icon={<Users/>} label="Ministries & Sectors" onClick={()=>go('admin')}/>
 </div>
 <div className="sidebar-bottom"><div className="mini-status"><span className="live-dot"/>Backend connected<div className="mini-url">localhost:8080</div></div><div className="sidebar-user"><div className="avatar">{(user?.name||'U').slice(0,1).toUpperCase()}</div><div><b>{user?.name||'User'}</b><small>{user?.role||'USER'}</small></div></div></div>
 </aside>}
function NavItem({icon,label,active,onClick}){return <button className={'nav-item '+(active?'active':'')} onClick={onClick}>{React.cloneElement(icon,{size:18})}<span>{label}</span>{active&&<ChevronRight size={15} className="nav-chevron"/>}</button>}
function Topbar({user,onLogout,onMenu}){return <header className="topbar"><button className="mobile-menu" onClick={onMenu}><Menu/></button><div className="crumb"><span>SETU</span><ChevronRight size={14}/><b>National Project View</b></div><div className="top-actions"><button className="top-action" onClick={()=>window.dispatchEvent(new CustomEvent('setu-add-project'))}><Plus size={16}/> Add Project</button><button className="icon-button"><CircleHelp size={18}/></button><div className="top-avatar">{(user?.name||'U').slice(0,1).toUpperCase()}</div><button className="icon-button" onClick={onLogout} title="Logout"><LogOut size={17}/></button></div></header>}

function Dashboard({onProject,onProjects,onRisk,onChat}){
 const [data,setData]=useState(null),[projects,setProjects]=useState([]),[loading,setLoading]=useState(true),[hero,setHero]=useState(0)
 useEffect(()=>{Promise.all([api.dashboard(),api.projects()]).then(([d,p])=>{setData(d);setProjects(p||[])}).catch(()=>{}).finally(()=>setLoading(false));const t=setInterval(()=>setHero(h=>(h+1)%HEROES.length),7000);return()=>clearInterval(t)},[])
 const statusEntries=Object.entries(data?.projectsByStatus||{}),riskEntries=Object.entries(data?.projectsByRiskLevel||{})
 return <div className="page-stack">
  <section className="hero"><img src={HEROES[hero].image}/><div className="hero-shade"/><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-line"/> NATIONAL PROJECT MONITORING</div><h1>{HEROES[hero].title}</h1><p>{HEROES[hero].sub}</p><div className="hero-actions"><button className="primary" onClick={onProjects}>Explore projects <ArrowRight size={17}/></button><button className="glass" onClick={onChat}><Sparkles size={17}/> Ask SETU</button></div></div><div className="hero-dots">{HEROES.map((_,i)=><button key={i} className={i===hero?'active':''} onClick={()=>setHero(i)}/>)}</div></section>
  <div className="section-head"><div><div className="eyebrow dark">LIVE SYSTEM VIEW</div><h2>Project pulse</h2><p>Signals from the connected Spring Boot backend.</p></div><button className="secondary" onClick={()=>location.reload()}><RefreshCw size={15}/> Refresh</button></div>
  <section className="metrics-grid">
   <Metric icon={<Building2/>} label="Total projects" value={data?.totalProjects??'—'} tone="blue"/>
   <Metric icon={<Activity/>} label="On track" value={data?.projectsByStatus?.ON_TRACK??0} tone="green"/>
   <Metric icon={<AlertTriangle/>} label="Active alerts" value={data?.activeAlertsCount??0} tone="amber"/>
   <Metric icon={<ShieldCheck/>} label="Critical alerts" value={data?.criticalAlertsCount??0} tone="red"/>
  </section>
  <section className="grid-2">
   <div className="panel"><div className="panel-head"><div><h3>Project status</h3><p>Current portfolio distribution</p></div><Activity size={19}/></div><div className="bar-list">{statusEntries.length?statusEntries.map(([k,v])=><div className="bar-row" key={k}><div className="bar-label"><span>{pretty(k)}</span><b>{v}</b></div><div className="track"><div className={'fill '+statusTone(k)} style={{width:`${Math.min(100,(v/(data?.totalProjects||1))*100)}%`}}/></div></div>):<Empty text="No project status data yet"/>}</div></div>
   <div className="panel"><div className="panel-head"><div><h3>Risk profile</h3><p>Latest generated risk scores</p></div><Zap size={19}/></div><div className="risk-stack">{riskEntries.length?riskEntries.map(([k,v])=><div className="risk-row" key={k}><span className={'risk-pill '+k.toLowerCase()}>{k}</span><b>{v}</b></div>):<Empty text="Generate a risk score to populate this view"/>}</div><button className="text-link" onClick={()=>onRisk(data?.topRiskProjects?.[0]?.projectId)} disabled={!data?.topRiskProjects?.length}>Run risk prediction on top project <ArrowRight size={15}/></button></div>
  </section>
  <section className="panel"><div className="panel-head"><div><h3>Highest-risk projects</h3><p>Top 5 projects returned by the dashboard API</p></div><button className="secondary small" onClick={()=>onChat()}><MessageCircle size={15}/> Ask about a project</button></div><div className="table-wrap"><table><thead><tr><th>Project</th><th>Risk score</th><th>Level</th><th>Action</th></tr></thead><tbody>{(data?.topRiskProjects||[]).map(p=><tr key={p.projectId}><td><button className="table-project" onClick={()=>onProject(p.projectId)}><span className="project-icon"><Building2 size={16}/></span><span><b>{p.name}</b><small>Project #{p.projectId}</small></span></button></td><td><div className="score"><strong>{Number(p.riskScoreValue||0).toFixed(1)}</strong><div className="score-track"><span style={{width:`${Math.min(100,Number(p.riskScoreValue||0))}%`}}/></div></div></td><td><span className={'risk-pill '+String(p.riskLevel||'').toLowerCase()}>{pretty(p.riskLevel)}</span></td><td><button className="outline-button" onClick={()=>onRisk(p.projectId)}>Risk prediction</button></td></tr>)}</tbody></table>{!data?.topRiskProjects?.length&&<Empty text="No risk-scored projects available yet."/>}</div></section>
  <section className="insight-strip"><div className="insight-icon"><Sparkles/></div><div><b>SETU early-action layer</b><span>Generate a project risk score to turn cost and schedule signals into an actionable risk tier and contributing factors.</span></div><button onClick={()=>onRisk(data?.topRiskProjects?.[0]?.projectId)} disabled={!data?.topRiskProjects?.length}>Run prediction <ArrowRight size={16}/></button></section>
 </div>
}
function Metric({icon,label,value,tone}){return <div className="metric"><div className={'metric-icon '+tone}>{icon}</div><div><span>{label}</span><strong>{value}</strong></div><TrendingUp size={16} className="metric-trend"/></div>}

function Projects({onProject,onRisk}){const [items,setItems]=useState([]),[status,setStatus]=useState(''),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[showAdd,setShowAdd]=useState(false)
 useEffect(()=>{const load=()=>{setLoading(true);api.projects(status).then(setItems).catch(()=>setItems([])).finally(()=>setLoading(false))};load();const h=()=>setShowAdd(true);window.addEventListener('setu-add-project',h);return()=>window.removeEventListener('setu-add-project',h)},[status])
 const filtered=useMemo(()=>items.filter(p=>[p.name,p.ministryName,p.sectorName,p.implementingAgency,p.status].filter(Boolean).join(' ').toLowerCase().includes(search.toLowerCase())),[items,search])
 return <div className="page-stack"><div className="section-head"><div><div className="eyebrow dark">PORTFOLIO</div><h2>Projects</h2><p>Monitor every connected project and launch risk prediction from its details.</p></div><button className="primary dark-btn" onClick={()=>setShowAdd(true)}><Plus size={16}/> Add project</button></div><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search projects, ministries, agencies…" value={search} onChange={e=>setSearch(e.target.value)}/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['ON_TRACK','DELAYED','AT_RISK','COMPLETED','STALLED'].map(s=><option key={s}>{s}</option>)}</select></div><div className="panel"><div className="table-wrap"><table><thead><tr><th>Project</th><th>Ministry</th><th>Agency</th><th>Progress</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(p=><tr key={p.projectId}><td><button className="table-project" onClick={()=>onProject(p.projectId)}><span className="project-icon"><Building2 size={16}/></span><span><b>{p.name}</b><small>#{p.projectId} · {p.sectorName||'Unassigned sector'}</small></span></button></td><td>{p.ministryName||'—'}</td><td>{p.implementingAgency||'—'}</td><td><div className="progress-cell"><span>{Number(p.physicalProgressPercent||0).toFixed(0)}%</span><div className="score-track"><span style={{width:`${Math.min(100,Math.max(0,p.physicalProgressPercent||0))}%`}}/></div></div></td><td><span className={'status-pill '+String(p.status||'').toLowerCase()}>{pretty(p.status)}</span></td><td><button className="icon-action" onClick={()=>onRisk(p.projectId)} title="Risk prediction"><Zap size={16}/></button></td></tr>)}</tbody></table>{loading?<Empty text="Loading projects…"/>:!filtered.length?<Empty text="No projects match your filters."/>:null}</div></div>{showAdd&&<AddProject onClose={()=>setShowAdd(false)} onCreated={p=>{setShowAdd(false);setItems(x=>[p,...x])}}/>}</div>}

function ProjectDetail({id,onBack,onRisk,onChat}){const [p,setP]=useState(null),[risk,setRisk]=useState(null);useEffect(()=>{api.project(id).then(setP).catch(()=>{});api.latestRisk(id).then(setRisk).catch(()=>setRisk(null))},[id]);if(!p)return <Empty text="Loading project…"/>;return <div className="page-stack"><button className="back-link" onClick={onBack}>← Back to projects</button><section className="detail-hero"><div><div className="eyebrow dark">PROJECT #{p.projectId}</div><h2>{p.name}</h2><p>{p.ministryName||'Ministry not assigned'} · {p.sectorName||'Sector not assigned'}</p></div><div className="detail-actions"><button className="glass-light" onClick={onChat}><MessageCircle size={16}/> Ask SETU</button><button className="primary" onClick={()=>onRisk(id)}><Zap size={16}/> Risk prediction</button></div></section><section className="metrics-grid four"><Metric icon={<TrendingUp/>} label="Physical progress" value={`${Number(p.physicalProgressPercent||0).toFixed(0)}%`} tone="green"/><Metric icon={<Database/>} label="Approved cost" value={`₹${Number(p.approvedCost||0).toLocaleString('en-IN')} Cr`} tone="blue"/><Metric icon={<Clock3/>} label="Schedule" value={p.revisedEndDate||p.scheduledEndDate||'—'} tone="amber"/><Metric icon={<ShieldCheck/>} label="Risk" value={risk?.riskLevel||'Not scored'} tone={String(risk?.riskLevel||'').toLowerCase()==='critical'?'red':'blue'}/></section><div className="grid-2"><div className="panel detail-card"><h3>Project profile</h3><Info label="Implementing agency" value={p.implementingAgency}/><Info label="Start date" value={p.startDate}/><Info label="Scheduled end" value={p.scheduledEndDate}/><Info label="Revised end" value={p.revisedEndDate}/><Info label="Cumulative expenditure" value={p.cumulativeExpenditure?`₹${Number(p.cumulativeExpenditure).toLocaleString('en-IN')} Cr`:'—'}/><Info label="Last updated" value={p.lastUpdated?new Date(p.lastUpdated).toLocaleString():'—'}/></div><div className="panel detail-card"><div className="panel-head"><div><h3>Latest risk intelligence</h3><p>Returned by the Spring Boot risk API.</p></div><Zap size={18}/></div>{risk?<><div className="risk-score-large"><strong>{Number(risk.riskScoreValue||0).toFixed(1)}</strong><span>risk score</span><span className={'risk-pill '+String(risk.riskLevel).toLowerCase()}>{risk.riskLevel}</span></div><div className="factor"><b>Contributing factors</b><p>{risk.contributingFactors||'No factors returned.'}</p></div><small className="muted">Generated {risk.generatedAt?new Date(risk.generatedAt).toLocaleString():'—'}</small></>:<Empty text="No risk score yet. Run prediction to generate one."/>}<button className="outline-button full" onClick={()=>onRisk(id)}><Zap size={15}/> {risk?'Generate fresh prediction':'Run risk prediction'}</button></div></div></div>}
function Info({label,value}){return <div className="info-row"><span>{label}</span><b>{value||'—'}</b></div>}

function Alerts(){const [items,setItems]=useState([]);useEffect(()=>{api.alerts().then(setItems).catch(()=>setItems([]))},[]);const ack=async id=>{try{const a=await api.acknowledgeAlert(id);setItems(x=>x.map(i=>i.alertId===id?a:i))}catch{}};return <div className="page-stack"><div className="section-head"><div><div className="eyebrow dark">ATTENTION CENTER</div><h2>Alerts</h2><p>Active signals created by the risk engine.</p></div></div><div className="alert-grid">{items.map(a=><div className={'alert-card '+String(a.severity||'').toLowerCase()} key={a.alertId}><div className="alert-top"><span className="risk-pill">{a.severity}</span><span>{a.createdAt?new Date(a.createdAt).toLocaleString():''}</span></div><h3>{a.projectName}</h3><p>{a.message}</p><button className="secondary small" disabled={a.acknowledged} onClick={()=>ack(a.alertId)}>{a.acknowledged?<><CheckCircle2 size={15}/> Acknowledged</>:<>Acknowledge</>}</button></div>)}{!items.length&&<div className="panel"><Empty text="No active alerts."/></div>}</div></div>}

function Reports(){return <div className="page-stack"><div className="section-head"><div><div className="eyebrow dark">DECISION SUPPORT</div><h2>Reports</h2><p>A clean reporting workspace built around the dashboard data already exposed by SETU.</p></div><button className="secondary" onClick={()=>window.print()}><FileText size={16}/> Print view</button></div><div className="report-grid"><div className="report-card dark-report"><span>Portfolio health</span><strong>Live</strong><p>Use the Overview page for the latest project, risk and alert distribution.</p></div><div className="report-card"><span>Risk register</span><strong>Top 5</strong><p>Highest-risk projects are returned by <code>/api/dashboard/summary</code>.</p></div><div className="report-card"><span>Project register</span><strong>All projects</strong><p>Filter and inspect projects through the connected project API.</p></div></div></div>}

function Admin(){const [mins,setMins]=useState([]),[secs,setSecs]=useState([]),[tab,setTab]=useState('ministries'),[name,setName]=useState(''),[dept,setDept]=useState('');useEffect(()=>{api.ministries().then(setMins).catch(()=>{});api.sectors().then(setSecs).catch(()=>{})},[]);const add=async()=>{if(!name.trim())return;try{if(tab==='ministries'){const x=await api.createMinistry({name,department:dept});setMins(v=>[...v,x])}else{const x=await api.createSector({name});setSecs(v=>[...v,x])}setName('');setDept('')}catch(e){alert(e.message)}};return <div className="page-stack"><div className="section-head"><div><div className="eyebrow dark">REFERENCE DATA</div><h2>Ministries & sectors</h2><p>Manage the reference lists used when creating projects.</p></div></div><div className="admin-layout"><div className="panel"><div className="tabs"><button className={tab==='ministries'?'active':''} onClick={()=>setTab('ministries')}>Ministries</button><button className={tab==='sectors'?'active':''} onClick={()=>setTab('sectors')}>Sectors</button></div><div className="admin-list">{(tab==='ministries'?mins:secs).map(x=><div className="admin-item" key={x.ministryId||x.sectorId}><div className="project-icon"><Building2 size={15}/></div><div><b>{x.name}</b><small>{x.department||'Sector reference'}</small></div></div>)}</div></div><div className="panel add-reference"><h3>Add {tab==='ministries'?'ministry':'sector'}</h3><input placeholder="Name" value={name} onChange={e=>setName(e.target.value)}/>{tab==='ministries'&&<input placeholder="Department (optional)" value={dept} onChange={e=>setDept(e.target.value)}/>}<button className="primary dark-btn" onClick={add}><Plus size={16}/> Add</button></div></div></div>}

function AddProject({onClose,onCreated}){const [mins,setMins]=useState([]),[secs,setSecs]=useState([]),[form,setForm]=useState({name:'',ministryId:'',sectorId:'',implementingAgency:'',approvedCost:'',revisedCost:'',cumulativeExpenditure:'',startDate:'',scheduledEndDate:'',revisedEndDate:'',physicalProgressPercent:''}),[busy,setBusy]=useState(false);useEffect(()=>{api.ministries().then(setMins).catch(()=>{});api.sectors().then(setSecs).catch(()=>{})},[]);const set=(k,v)=>setForm(f=>({...f,[k]:v}));const submit=async e=>{e.preventDefault();setBusy(true);try{const body={...form,ministryId:form.ministryId?Number(form.ministryId):null,sectorId:form.sectorId?Number(form.sectorId):null,approvedCost:Number(form.approvedCost),revisedCost:form.revisedCost?Number(form.revisedCost):null,cumulativeExpenditure:form.cumulativeExpenditure?Number(form.cumulativeExpenditure):null,physicalProgressPercent:form.physicalProgressPercent?Number(form.physicalProgressPercent):0};const p=await api.createProject(body);onCreated(p)}catch(err){alert(err.message)}finally{setBusy(false)}};return <div className="modal-backdrop"><form className="modal large" onSubmit={submit}><div className="modal-head"><div><span className="eyebrow dark">NEW PROJECT</span><h2>Add project</h2></div><button type="button" className="icon-button" onClick={onClose}><X/></button></div><div className="form-grid"><Field label="Project name*" value={form.name} onChange={v=>set('name',v)} required/><Field label="Implementing agency" value={form.implementingAgency} onChange={v=>set('implementingAgency',v)}/><SelectField label="Ministry" value={form.ministryId} onChange={v=>set('ministryId',v)} options={mins.map(x=>[x.ministryId,x.name])}/><SelectField label="Sector" value={form.sectorId} onChange={v=>set('sectorId',v)} options={secs.map(x=>[x.sectorId,x.name])}/><Field label="Approved cost (₹ Cr)*" type="number" value={form.approvedCost} onChange={v=>set('approvedCost',v)} required/><Field label="Revised cost (₹ Cr)" type="number" value={form.revisedCost} onChange={v=>set('revisedCost',v)}/><Field label="Cumulative expenditure (₹ Cr)" type="number" value={form.cumulativeExpenditure} onChange={v=>set('cumulativeExpenditure',v)}/><Field label="Physical progress (%)" type="number" value={form.physicalProgressPercent} onChange={v=>set('physicalProgressPercent',v)}/><Field label="Start date" type="date" value={form.startDate} onChange={v=>set('startDate',v)}/><Field label="Scheduled end" type="date" value={form.scheduledEndDate} onChange={v=>set('scheduledEndDate',v)}/><Field label="Revised end" type="date" value={form.revisedEndDate} onChange={v=>set('revisedEndDate',v)}/></div><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary dark-btn" disabled={busy}>{busy?'Creating…':'Create project'}</button></div></form></div>}
function Field({label,value,onChange,type='text',required}){return <label className="field"><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} required={required}/></label>}
function SelectField({label,value,onChange,options}){return <label className="field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}><option value="">Not assigned</option>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}

function RiskModal({projectId,onClose}){const [risk,setRisk]=useState(null),[busy,setBusy]=useState(true),[err,setErr]=useState('');useEffect(()=>{api.generateRisk(projectId).then(setRisk).catch(e=>setErr(e.message)).finally(()=>setBusy(false))},[projectId]);return <div className="modal-backdrop"><div className="modal risk-modal"><div className="modal-head"><div><span className="eyebrow dark">EARLY WARNING ENGINE</span><h2>Risk prediction</h2><p>Project #{projectId}</p></div><button className="icon-button" onClick={onClose}><X/></button></div>{busy?<div className="prediction-loading"><div className="orb"><Zap/></div><h3>Running prediction…</h3><p>SETU is sending the project profile to the connected risk service.</p></div>:err?<div className="error-state"><AlertTriangle/><h3>Prediction unavailable</h3><p>{err}</p><button className="secondary" onClick={onClose}>Close</button></div>:<><div className="prediction-score"><div><span>Risk score</span><strong>{Number(risk?.riskScoreValue||0).toFixed(1)}</strong></div><span className={'risk-pill '+String(risk?.riskLevel||'').toLowerCase()}>{risk?.riskLevel}</span></div><div className="factor-box"><b>Contributing factors</b><p>{risk?.contributingFactors||'No contributing factors returned.'}</p></div><div className="prediction-note"><Sparkles size={17}/><span>This prediction is generated by the backend risk endpoint and persisted as the project's latest risk score.</span></div><button className="primary dark-btn full" onClick={onClose}>Done</button></>}</div></div>}

function cleanChatText(value){
 if(value==null) return '';
 let s=String(value).replace(/```[\s\S]*?```/g,m=>m.replace(/```[a-zA-Z0-9_-]*\n?/,'').replace(/```/g,''));
 s=s.replace(/\r/g,'').replace(/^\s{0,3}#{1,6}\s*/gm,'').replace(/^\s*[-*+]\s+/gm,'• ').replace(/^\s*\d+[.)]\s+/gm,'');
 s=s.replace(/\*\*(.*?)\*\*/g,'$1').replace(/__(.*?)__/g,'$1').replace(/\*(.*?)\*/g,'$1').replace(/_(.*?)_/g,'$1').replace(/`([^`]*)`/g,'$1');
 s=s.replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,'$1');
 s=s.replace(/^[ \t]*#{1,6}[ \t]*/gm,'');
 return s.replace(/[ \t]+\n/g,'\n').replace(/\n{3,}/g,'\n\n').trim();
}

function Chatbot({onClose}){const [messages,setMessages]=useState([{sender:'BOT',content:'Hello. I’m SETU. Ask me about projects, risk, progress, cost or schedule signals.'}]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[sessionId,setSessionId]=useState(null);const send=async()=>{if(!text.trim()||busy)return;const q=text.trim();setText('');setMessages(m=>[...m,{sender:'USER',content:q}]);setBusy(true);try{const r=await api.chat({sessionId,question:q});setSessionId(r.sessionId);setMessages(m=>[...m,{sender:'BOT',content:cleanChatText(r.answer)}])}catch(e){setMessages(m=>[...m,{sender:'BOT',content:`I couldn't complete that request: ${e.message}`}])}finally{setBusy(false)}};return <div className="chat-panel"><div className="chat-head"><div className="chat-brand"><div className="bot-orb"><Sparkles size={17}/></div><div><b>Ask SETU</b><small>Project intelligence assistant</small></div></div><button className="icon-button" onClick={onClose}><X/></button></div><div className="chat-messages">{messages.map((m,i)=><div className={'bubble-row '+m.sender.toLowerCase()} key={i}><div className="bubble">{m.content}</div></div>)}{busy&&<div className="bubble-row bot"><div className="bubble typing"><i/><i/><i/></div></div>}</div><div className="chat-suggestions"><button onClick={()=>setText('Which projects have the highest risk?')}>Highest-risk projects</button><button onClick={()=>setText('Show me the current alert picture')}>Alert picture</button></div><div className="chat-input"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask about a project…"/><button onClick={send} disabled={busy}><ArrowRight size={18}/></button></div></div>}

function Login({onLogin}){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const nav=useNavigate();const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const u=await api.login({email,password});localStorage.setItem('setu_token',u.token);localStorage.setItem('setu_user',JSON.stringify(u));onLogin(u)}catch(e){setError(e.message)}finally{setBusy(false)}};return <AuthShell><form className="auth-card" onSubmit={submit}><div className="auth-logo"><div className="brand-mark"><span>S</span></div><div><b>SETU</b><small>Project Intelligence</small></div></div><div className="eyebrow dark">SECURE ACCESS</div><h1>Welcome back.</h1><p>Sign in to your national project intelligence workspace.</p>{error&&<div className="error-banner">{error}</div>}<Field label="Email" value={email} onChange={setEmail} required/><Field label="Password" type="password" value={password} onChange={setPassword} required/><button className="primary dark-btn full" disabled={busy}>{busy?'Signing in…':'Sign in'} <ArrowRight size={16}/></button><div className="auth-foot">New to SETU? <button type="button" onClick={()=>nav('/register')}>Create an account</button></div></form></AuthShell>}
function Register({onLogin}){const [form,setForm]=useState({name:'',email:'',password:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');const nav=useNavigate();const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{await api.register(form);const u=await api.login({email:form.email,password:form.password});localStorage.setItem('setu_token',u.token);localStorage.setItem('setu_user',JSON.stringify(u));onLogin(u)}catch(e){setError(e.message)}finally{setBusy(false)}};return <AuthShell><form className="auth-card" onSubmit={submit}><div className="auth-logo"><div className="brand-mark"><span>S</span></div><div><b>SETU</b><small>Project Intelligence</small></div></div><div className="eyebrow dark">CREATE ACCESS</div><h1>Start with SETU.</h1><p>Create an account to access project monitoring and intelligence.</p>{error&&<div className="error-banner">{error}</div>}<Field label="Full name" value={form.name} onChange={v=>setForm(f=>({...f,name:v}))} required/><Field label="Email" value={form.email} onChange={v=>setForm(f=>({...f,email:v}))} required/><Field label="Password" type="password" value={form.password} onChange={v=>setForm(f=>({...f,password:v}))} required/><button className="primary dark-btn full" disabled={busy}>{busy?'Creating…':'Create account'} <ArrowRight size={16}/></button><div className="auth-foot">Already have access? <button type="button" onClick={()=>nav('/login')}>Sign in</button></div></form></AuthShell>}
function AuthShell({children}){return <div className="auth-shell"><div className="auth-image"><img src="https://upload.wikimedia.org/wikipedia/commons/3/3f/Aerial_view_of_Central_Vista%2C_New_Delhi_%2C_India.jpg"/><div className="hero-shade"/><div className="auth-copy"><div className="eyebrow">NATIONAL PROJECT INTELLIGENCE</div><h2>Turn infrastructure data into early action.</h2><p>SETU connects portfolio visibility, risk intelligence and project conversations in one focused workspace.</p></div></div><div className="auth-side">{children}</div></div>}
function Empty({text}){return <div className="empty"><CircleHelp size={18}/><span>{text}</span></div>}
function pretty(s){return String(s||'').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase())}
function statusTone(s){return s==='ON_TRACK'?'green':s==='DELAYED'?'amber':s==='AT_RISK'?'red':'blue'}

createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>)
